server:
  port: 9527

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 100
        min-idle: 5
        connection-test-query: select 1
        pool-name: BusApiHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://111.200.216.79:10543/za_bus_api
          url: jdbc:postgresql://192.168.6.160:10543/za_bus_api
        # 数据源-2，名称为 test
  #        test:
  #          username: root
  #          password: 123456
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  #          url: jdbc:mysql://127.0.0.1:3306/bus_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  rabbitmq:
#    host: 192.168.6.158
#    port: 5673
#    password: iotmq
#    username: iotmq
#    publisherConfirms: true
#    publisherReturns: true
#    virtualHost: iot
    host: 127.0.0.1
    port: 5672
    password: bus
    username: bus
    publisherConfirms: true
    publisherReturns: true
    virtualHost: busapi

  jackson:
    #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write_dates_as_timestamps: false

  redis:
    host: 192.168.6.160
    port: 10637
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.phlink.bus.api.*.domain
  mapper-locations: classpath:mapper/*/*.xml
  config-location: classpath:mybatis-config.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  type-enums-package: com.phlink.bus.api.*.domain.enums
  type-handlers-package: com.phlink.bus.api.common.mybatis.typehandler.*

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


bus-api:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login**/**,/logout/**,/region/**,/regist,/user/check/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/swagger-resources/**,/**/down-template,/trip/v2/face-attendance/**
    # token有效期，单位秒
    jwtTimeOut: 72000
  im:
    url: https://111.200.216.74:1447/admin-api
    username: superadmin
    password: superadmin
    companyId: mBN2AEmE39qu3DQ93DUqhVE
    busOrgId: 1UoWBpDZQtws1CoiKTC10s
    routeOrgId: RMI5_G_HS2MjR31WGlWYQc
    guardianOrgId: 8iGYfl7MTJcv0Td9ZLKHF8
    teacherOrgId: T9bUT_1BQJkrM4SWleLhyE
    cron: 0 0 */1 * * ?
  dvr:
    account: admin
    password: admin
    cron: 0 0 */1 * * ?
    frequency: 15
  iot:
    url: http://111.200.216.79:19091/api
    username: tenant@thingsboard.org
    password: tenant
    cron: 0 0 */1 * * ?
    gateway: 672a15a0-b2ca-11e9-9193-f3dbd204902d

javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests:
    log: false
    # to exclude images, css, fonts and js urls from the monitoring:
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    #http-transform-pattern: \d+
    # to add basic auth:
    authorized-users: admin:admin
    # to change the default storage directory:
    storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance

#告警阈值
alarm-config:
  #过期时间
  pexpire: 3600000
  #次数
  times: 3
  #车速
  speed: 60.0
  #超速时间级别升级
  speed-time-up-minute: 3
  #路线偏移距离告警
  route-offset-distance: 70
  #路线偏移距离告警升级
  route-offset-distance-up: 200
  #离线告警时间
  offline-minute: 5
  #到站距离
  stop-distance: 200
  #到站迟到时间
  stop-time-minute: 10
  #离线时长
  offline-time-minute: 5


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.6.159:22122
  host: 111.200.216.79
  port: 18082
