server:
  port: 9529

spring:
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    redisson:
      config: classpath:redisson.yaml

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: bus
    username: bus
    publisherConfirms: true
    publisherReturns: true
    virtualHost: busapi


management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

websocket:
  server:
    host: 127.0.0.1
    port: 9660

push:
  key: 57038efc1e5b673fdc6a81bf
  secret: 8227fec9ed1baf0fb24a55a2
