server:
  port: 9529

spring:
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.6.160
    port: 10637
#    host: 127.0.0.1
#    port: 6379
#    password: redispwd
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  rabbitmq:
    host: 192.168.6.158
    port: 5673
    password: iotmq
    username: iotmq
    publisherConfirms: true
    publisherReturns: true
    virtualHost: iot
#    host: 127.0.0.1
#    port: 5672
#    password: bus
#    username: bus
#    publisherConfirms: true
#    publisherReturns: true
#    virtualHost: busapi


management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

websocket:
  server:
    host: 127.0.0.1
    port: 9660

push:
  key: 57038efc1e5b673fdc6a81bf
  secret: 8227fec9ed1baf0fb24a55a2
